// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen; the struct helpers it emits are not exercised.
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// [control] Registers the node types with the host api of an engine
/// (`const AudHostApi*`); AUD_OK or the first error code.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>()
external int aud_dsp_sampler_register(ffi.Pointer<ffi.Void> host_api);

const String AUD_DSP_SAMPLER_SFZ_TYPE_ID = 'aud.sampler.sfz';

const int AUD_SFZ_SAMPLER_KEY_FILE = 0;

const int AUD_SFZ_SAMPLER_KEY_TEXT = 2;

const int AUD_SFZ_SAMPLER_KEY_VIRTUAL_PATH = 1;
